name: test-in-pull-request

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ develop, main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: config node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  automerge:
    name: Automerge
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""